## 00. PyTorch Fundamentals

In [ ]:
import torch
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
print(torch.__version__)

2.3.1+cu121


## Introduction to Tensors
### Creating Tensors

Pytorch tensors are created using "torch.Tensor()"

In [ ]:
#scalar
scalar=torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.item()

7

In [ ]:
#Vector
vector=torch.Tensor([7,7])
vector

tensor([7., 7.])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
#MATRIX
MATRIX=torch.tensor([[7,8],
                     [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX[1][1]

tensor(10)

In [ ]:
MATRIX.shape

torch.Size([2, 2])

###Random Tensors

In [ ]:
#Create a random Tensor of size (3, 4)
random_tensor=torch.rand(3,4)
random_tensor

tensor([[0.6565, 0.3591, 0.6632, 0.5789],
        [0.3623, 0.8643, 0.9651, 0.5608],
        [0.1294, 0.8362, 0.9711, 0.8832]])

In [ ]:
random_tensor.ndim

2

In [ ]:
#Create a random tensor with similar shape to an image tensor
random_image_size_tensor=torch.rand(size=(224,224,3)) # height, width, colour channels
random_image_size_tensor, random_image_size_tensor.ndim

(tensor([[[0.6858, 0.2718, 0.3772],
          [0.9766, 0.3186, 0.4617],
          [0.4075, 0.9984, 0.9313],
          ...,
          [0.6798, 0.3554, 0.3534],
          [0.9962, 0.6305, 0.7315],
          [0.1204, 0.1045, 0.3291]],
 
         [[0.6230, 0.9678, 0.5919],
          [0.5941, 0.2966, 0.2274],
          [0.0081, 0.2236, 0.4829],
          ...,
          [0.5258, 0.5799, 0.5490],
          [0.8739, 0.5919, 0.6042],
          [0.1021, 0.7801, 0.1475]],
 
         [[0.9727, 0.4511, 0.2384],
          [0.5639, 0.0890, 0.6128],
          [0.1227, 0.9832, 0.3700],
          ...,
          [0.7303, 0.8988, 0.9639],
          [0.9219, 0.0893, 0.9430],
          [0.4468, 0.0111, 0.1518]],
 
         ...,
 
         [[0.8985, 0.1797, 0.1397],
          [0.8017, 0.7720, 0.4755],
          [0.7818, 0.5552, 0.1017],
          ...,
          [0.0709, 0.7284, 0.7217],
          [0.8982, 0.6390, 0.4536],
          [0.5708, 0.1456, 0.2728]],
 
         [[0.9824, 0.3403, 0.4020],
          [0

##Zeros & Ones

In [ ]:
#Create a tensor of all zeros
zeros=torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
# Create a tensor of all ones
ones=torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

### Creating a range of Tensors & tensor-like

In [ ]:
#Use torch.raneg()
one_to_ten=torch.arange(start=1, end=1000, step=77)
one_to_ten

tensor([  1,  78, 155, 232, 309, 386, 463, 540, 617, 694, 771, 848, 925])

In [ ]:
#Creating Tensors like
ten_zeros=torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

###Tensor Datatypes

In [ ]:
#Float 32 tensor
float_32_tensor=torch.tensor([3.0, 6.0, 9.0],
                             dtype=None, #datatype of sensor
                             device=None, # What device your tensor is on
                             requires_grad=False) # Whether or not to track gradients with this tensor
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
float_16_tensor= float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
float_32_tensor*float_16_tensor

tensor([ 9., 36., 81.])

###Manipulating Tensors (Tensor Operations)
Tensor Operations include:
*Addition
*Subtraction
*Multiplication
*Division
*Matrix Multiplication

In [ ]:
#Create a tensor
tensor=torch.tensor([1,2,3])
tensor+10

tensor([11, 12, 13])

In [ ]:
#Multiply
tensor*10

tensor([10, 20, 30])

In [ ]:
#Subtract
tensor-10

tensor([-9, -8, -7])

In [ ]:
#Try out pytorch inbuilt fucntion
torch.mul(tensor, 10)

tensor([10, 20, 30])

###Matrix Multiplication

Two ways of performing multiplication in neural networks and deep learning:
1. Element-wise multiplication
2. Matrix multiplication (dot product)


In [ ]:
%%time
val=0
for i in range(len(tensor)):
  val+=tensor[i]*tensor[i]
print(val)

tensor(14)
CPU times: user 1.22 ms, sys: 39 µs, total: 1.26 ms
Wall time: 9.24 ms


In [ ]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 485 µs, sys: 0 ns, total: 485 µs
Wall time: 14.3 ms


tensor(14)

##Rules of Matrix Multiplication:
1. The **inner dimensions** must match
2. The resulting matrix has the shape of the **outer dimensions**

In [ ]:
torch.matmul(torch.rand(2,3), torch.rand(3,2))

tensor([[0.4422, 0.3242],
        [0.6734, 0.3320]])

###One of the most common errors in deep learning: Shape Errors

In [ ]:
tensor_A=torch.tensor([[1,2],
                       [3,4],
                       [5,6]])

tensor_B=torch.tensor([[7,10],
                       [8,11],
                       [9,12]])

#torch.mm(tA,tB) is an alias for torch.matmul

torch.matmul(tensor_A,tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [ ]:
tensor_A.shape, tensor_B.shape

#To fix our tensor shape issue, we can manipulate the shape of one of our tensors using a **Transpose**

#A transpose switches the axes or dimensions of a given tensor

In [ ]:
tensor_B.T, tensor_B.T.shape

In [ ]:
torch.matmul(tensor_A,tensor_B.T)

##Finding the min, max, sum, etc. (Tensor aggregation)


In [ ]:
x=torch.arange(0,100,10)
x

In [ ]:
torch.min(x), x.min()

In [ ]:
torch.max(x),x.max()

In [ ]:
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

In [ ]:
torch.sum(x)

###Finding postional min & postional max of tensors

In [ ]:
#find the position in a tensor that has the minimum value with argmin()
x.argmin(), x.argmax()

In [ ]:
x=torch.arange(0,100,10)
x

#Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping- reshapes an input tensor to a defined shape

* View- Return a view of an input tensor of certain shape but keep the same memory as the original tensor

* Stacking- Concatenates a sequence of tensors along a new dimension (dim), all tensors must be same size.

* Squeeze- removes all '1' dimensions from a tensor

* Unsqueeze- add a '1' dimension to a target tensor

* Permute- Return a view of the input with dimensions permuted (swapped) in a certain way


In [ ]:
import torch
x=torch.arange(2.,10.)
x, x.shape

In [ ]:
# Add an extra dimension
x_reshaped=x.reshape(8,1)
x_reshaped, x_reshaped.shape

In [ ]:
#View
z=x.view(1,8)
z, z.shape

In [ ]:
# Stack tensors on top of each other
x_stack=torch.stack([x,x,x,x], dim=0)
x_stack

In [ ]:
# torch.squeeze() - removes all single dimensions from a target tensors
x=torch.zeros(2,1,2,1,2)
x.size()

In [ ]:
y=torch.squeeze(x)
y.size()

In [ ]:
y=torch.squeeze(x,0)
y.size()

In [ ]:
y=torch.squeeze(x,1)
y.size()

####torch.permute- rearranges dimensions of a target tensor in a specified order

In [ ]:
x_original=torch.rand(size=(224,224,3))

#permute the orginal tensor to rearrange the axis (or dim) order
x_permuted=x_original.permute(2,0,1)
x_permuted.size()

In [ ]:
x_original[0,0,0]=0.1234
x_original[0,0,0]=x_permuted[0,0,0]
x_permuted[0,0,0]

## Indexing (selecting data from tensors)

Indexing with PyTorch is similar to indexing with NumPy

In [ ]:
#Create a tensor
import torch
x=torch.arange(1,10).reshape(1,3,3)
x, x.shape

In [ ]:
#lets index on our new tensor
x[0]

In [ ]:
x[0][0]

In [ ]:
x[0][0][0]

In [ ]:
x[0][1][1]

In [ ]:
x[0][2][2]

In [ ]:
#get all values of 0th and 1st dimension but only index 1 of 2nd dimension
x[:,:,1]

In [ ]:
#get all values of the 0th dimension but only has the 1 index value of 1st and 2nd dimension
x[:,:,1]

In [ ]:
x[:,:,2]

##Pytorch tensors & NumPy

NumPy is a popular scientific Python numerical computing library.
And because of this, PyTorch has functionality to interact with it.

* Data in NumPy, want in PyTorch tensor -> torch.from_numpy(ndarray)
* PyTorch tensor -> NumPy -> torch.Tensor.numpy()

In [ ]:
#NumPy array to tensor
import torch
import numpy as np

array=np.arange(1.0,8.0)
tensor=torch.from_numpy(array)
array, tensor

In [ ]:
#Change the value of an array, what will this do to a tensor??
array=array+1
array,tensor

In [ ]:
tensor=torch.ones(7)
numpy_tensor=tensor.numpy()
tensor, numpy_tensor

In [ ]:
# Change tensor, what happens to `numpy_tensor`??

tensor=tensor+1
tensor,numpy_tensor

## Reproducability (trying to take random out of random)

In short how a neural network learns:
`start with random numbers-> tensor operation -> update random numbers to try and
make them better representations of the data-> again.. -> again.. -> again...`

To reduce the randomness in neural networks and PyTorch comes the concept of a **random seed**.

Essentially what the random seed does is "flavour" the randomness.

In [ ]:
import torch

#Create two random tensors
random_tensor_A=torch.rand(3,4)
random_tensor_B=torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A==random_tensor_B)

In [ ]:
# Let's make some random but reproducable tensors
import torch

# Set the random seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C=torch.rand(3,4)
torch.manual_seed(RANDOM_SEED)
random_tensor_D=torch.rand(3,4)
print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C==random_tensor_D)

## Running tensors and PyTorch objects on the GPUs (and making faster computations)

GPUs= faster computation on numbers, thanks to Cuda + NVIDIA hardware + PyTorch working behind the scenes to make everything good.

### 1. Getting a GPU

1. Using Google Colab for a free GPU (options to upgrade as well)
2. Use your own GPU
3. Use cloud computing- GCP, AWS, Azure, these services allow you to rent computers on the cloud and access them


In [ ]:
!nvidia-smi

Wed Aug 14 16:56:08 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   50C    P8              10W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

###2. Check for GPU access with PyTorch

In [ ]:
import torch
torch.cuda.is_available()

True

In [ ]:
#setup device agnostic code
device="cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [ ]:
#Count the number of devices
torch.cuda.device_count()

1